### ISSUE TITLE
mac shell 变色。。。。？？

### ISSUE THREAD

**Issue by systemctls** [chenjiandongx/how#2]
运行how man等后颜色变成灰色。。各种主题都会变

**Comment by chenjiandongx** [comment]
能否截个图来看，我没有 mac 机器。:joy:

**Comment by systemctls** [comment]
这个是iTemr2客户端。



这个是Mac自带的shell


😂好神奇。

Ps：刚在身边推荐了一波，好用到爆炸

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/65501677-fdeb8280-def3-11e9-8529-591ce85101be.png)

全凭想象吗

**Comment by Grainfills** [comment]
难受，我这边显示有图片的。我截图放到cos上。
Mac自带的，直接被带跑偏    https://cos.jinxm.club/picgo/iterm2.png <https://cos.jinxm.club/picgo/iterm2.png>

iterm的还算正常，只是显示还有部分灰灰的 	 https://cos.jinxm.club/picgo/iterm1.jpg

**Comment by systemctls** [comment]
有毒

**Comment by systemctls** [comment]
https://cos.jinxm.club/picgo/iterm1.jpg
https://cos.jinxm.club/picgo/iterm2.png

**Comment by chenjiandongx** [comment]
因为我设置的就是灰色 😂 ，不过看起来颜色匹配这个还做得不到位

**Comment by systemctls** [comment]
说明进入到了知识的荒野，怕灰就多记
