### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by Feeco-Li** [chenjiandongx/how#5]
sudo install how

Could not find a version that satisfies the requirement how (from versions: )
No matching distribution found for how

git clone --------------
cd how
pip install -r requirements.txt
chmod +x setup.py
python setup.py install

  File "setup.py", line 35
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 35, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by chenjiandongx** [comment]
那直接使用 pip 安装呢？
```shell
pip install how
```

**Comment by Feeco-Li** [comment]
Could not find a version that satisfies the requirement how (from versions: )
No matching distribution found for how

同样得到这个提示, 没关系了, 谢谢你的回复.我用其他的方法实现了.
function xx(){
input=$1;
'w3m https://chenchuanjia/linux-command/c/$input.html
}
给后来的,安装有问题的朋友们.
谢谢jiadongx

**Comment by chenjiandongx** [comment]
ok
